x-logging: &default-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  db:
    image: postgres:17
    container_name: bento-alephium-db
    <<: *default-logging
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-bento_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bento_password}
      POSTGRES_DB: ${POSTGRES_DB:-bento_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-bento_user} -d ${POSTGRES_DB:-bento_db}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bento-network

  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bento-alephium-indexer
    <<: *default-logging
    command: /app/bento run worker
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./examples/linx-indexer/config.toml:/app/config.toml
    networks:
      - bento-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bento-alephium-api
    <<: *default-logging
    command: /app/bento run server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - ./examples/linx-indexer/config.toml:/app/config.toml
    networks:
      - bento-network

  cli:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bento-alephium-cli
    <<: *default-logging
    command: tail -f /dev/null
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./examples/linx-indexer/config.toml:/app/config.toml
    networks:
      - bento-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yaml:ro
    restart: unless-stopped
    networks:
      - bento-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PROVISIONING_PATH=/etc/grafana/provisioning
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
    restart: unless-stopped
    networks:
      - bento-network

networks:
  bento-network:
    driver: bridge

volumes:
  postgres_data:
  grafana-data:
