x-logging: &default-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  db:
    image: postgres:17
    container_name: bento-alephium-db
    <<: *default-logging
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-bento_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bento_password}
      POSTGRES_DB: ${POSTGRES_DB:-bento_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-bento_user} -d ${POSTGRES_DB:-bento_db}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bento-network

  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bento-alephium-indexer
    <<: *default-logging
    command: /app/bento run worker
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./examples/linx-indexer/config.toml:/app/config.toml
    networks:
      - bento-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bento-alephium-api
    <<: *default-logging
    command: /app/bento run server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - ./examples/linx-indexer/config.toml:/app/config.toml
    networks:
      - bento-network

  cli:
    build:
      context: .
      dockerfile: Dockerfile.cli
    container_name: bento-alephium-cli
    <<: *default-logging
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./examples/linx-indexer/config.toml:/app/config.toml
      - ./examples/linx-indexer/migrations:/app/migrations
      - ./examples/linx-indexer/src/schema.rs:/app/src/schema.rs
    networks:
      - bento-network

networks:
  bento-network:
    driver: bridge

volumes:
  postgres_data:
