[worker]
database_url = "postgresql://postgres:postgres@localhost:5432/bento_alephium"
network = "mainnet"
request_interval = 5000
step = 1800000
backstep = 60000

[server]
port = "8080"

[backfill]
workers = 4
request_interval = 100 # 5 seconds
step = 1800000         # 30 minutes
backstep = 60000       # 1 minute backstep

[processors.transfers]
name = "transfers"
gas_payer_addresses = []
