[worker]
database_url = "postgresql://postgres:postgres@localhost:5432/bento_alephium"
network = "mainnet"
rpc_url = "https://alephium.linxlabs.org"
start = 1716560632750
step = 1800000
request_interval = 1000
workers = 2

[server]
port = "8080"

[backfill]
start = 1746594420000
stop = 1746598891136
request_interval = 1000

[processors.transfers]
name = "transfers"
gas_payer_addresses = ["1C44MNPDY8rNKwaeyrYCF2FPT6rXhNUNtP7fQv81PKjwq"]
